import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { FinishedProduct } from './types'

interface ReceiptData {
    receiptNo: string
    date: string
    customerName: string
    customerTaxId?: string
    customerAddress?: string
    customerEmail?: string
}

interface OrganizationInfo {
    name: string
    fiscalName?: string
    fiscalId?: string
    fiscalAddress?: string
    phone?: string
    email?: string
    footerMessage?: string
    logoUrl?: string
}

interface ReceiptItem {
    description: string
    quantity: number
    unitPrice: number
    total: number
}

export function generateReceipt(
    data: ReceiptData,
    org: OrganizationInfo,
    items: ReceiptItem[]
) {
    const doc = new jsPDF()

    // --- Header ---
    const marginLeft = 14
    let yPos = 20

    // Company Name (Big)
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text(org.name, marginLeft, yPos)
    yPos += 8

    // Fiscal Data (Small)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100)

    if (org.fiscalName) {
        doc.text(org.fiscalName, marginLeft, yPos)
        yPos += 5
    }
    if (org.fiscalId) {
        doc.text(`RFC/Tax ID: ${org.fiscalId}`, marginLeft, yPos)
        yPos += 5
    }
    if (org.fiscalAddress) {
        // Split address if too long
        const splitAddr = doc.splitTextToSize(org.fiscalAddress, 100)
        doc.text(splitAddr, marginLeft, yPos)
        yPos += (5 * splitAddr.length)
    }

    // Contact Info
    if (org.phone || org.email) {
        const contact = [org.phone, org.email].filter(Boolean).join(' | ')
        doc.text(contact, marginLeft, yPos)
        yPos += 8
    }

    // --- Receipt Info (Right Side) ---
    const rightColX = 140
    let rightY = 20

    doc.setFontSize(22)
    doc.setTextColor(0, 0, 0) // Black
    doc.text('RECEIPT', rightColX, rightY)

    doc.setFontSize(10)
    doc.setTextColor(100)
    rightY += 10
    doc.text(`No: ${data.receiptNo}`, rightColX, rightY)
    rightY += 5
    doc.text(`Date: ${data.date}`, rightColX, rightY)

    // --- Customer Info ---
    yPos += 10 // Spacing
    doc.setFontSize(11)
    doc.setTextColor(0)
    doc.setFont('helvetica', 'bold')
    doc.text('Bill To:', marginLeft, yPos)
    yPos += 5

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text(data.customerName, marginLeft, yPos)
    yPos += 5

    if (data.customerTaxId) {
        doc.text(`Tax ID: ${data.customerTaxId}`, marginLeft, yPos)
        yPos += 5
    }

    if (data.customerAddress) {
        doc.text(data.customerAddress, marginLeft, yPos)
        yPos += 5
    }

    // --- Items Table ---
    yPos += 10

    const tableBody = items.map(item => [
        item.description,
        item.quantity.toString(),
        `$${item.unitPrice.toFixed(2)}`,
        `$${item.total.toFixed(2)}`
    ])

    const totalAmount = items.reduce((sum, item) => sum + item.total, 0)

    autoTable(doc, {
        startY: yPos,
        head: [['Description', 'Qty', 'Unit Price', 'Total']],
        body: tableBody,
        theme: 'striped',
        headStyles: { fillColor: [22, 163, 74] }, // Green-600
        styles: { fontSize: 10 },
        columnStyles: {
            0: { cellWidth: 'auto' },
            1: { cellWidth: 20, halign: 'center' },
            2: { cellWidth: 30, halign: 'right' },
            3: { cellWidth: 30, halign: 'right' }
        },
        foot: [['', '', 'Total:', `$${totalAmount.toFixed(2)}`]],
        footStyles: { fillColor: [255, 255, 255], textColor: [0, 0, 0], fontStyle: 'bold', halign: 'right' }
    })

    // --- Footer ---
    const finalY = (doc as any).lastAutoTable.finalY + 20

    if (org.footerMessage) {
        doc.setFontSize(10)
        doc.setTextColor(100)
        doc.text(org.footerMessage, 105, finalY, { align: 'center' })
    }

    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text('Generated by Pikagummies', 105, 280, { align: 'center' })

    doc.save(`receipt-${data.receiptNo}.pdf`)
}
